### PR TITLE
Add staking cli test

### PR DESCRIPTION
**Pull request by sahith-narahari**
- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/develop/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added entries in `PENDING.md` with issue # 
- [ ] rereviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by sahith-narahari** [comment]
Please don't merge

**Comment by aaronc** [comment]
> Please don't merge

For this you can mark it as a draft again @sahith-narahari

**Comment by aaronc** [comment]
An easy way to modularize the helpers is to create a file like `x/staking/client/cli/test_helpers.go` and put `TxStakingEditValidator`, etc. as a function with `*Fixtures` as the first param. Ex:

```go
func TxStakingEditValidator(f  *Fixtures, from string, flags ...string) (bool, string, string) {
...
```

I think these functions can live in the modules they relate to. Would that work?

**Comment by sahith-narahari** [comment]
> An easy way to modularize the helpers is to create a file like `x/staking/client/cli/test_helpers.go` and put `TxStakingEditValidator`, etc. as a function with `*Fixtures` as the first param. Ex:
> 
> ```go
> func TxStakingEditValidator(f  *Fixtures, from string, flags ...string) (bool, string, string) {
> ...
> ```
> 
> I think these functions can live in the modules they relate to. Would that work?
> 
> /cc @anilCSE

This approach should be fine, will try to migrate for a module and update

**Comment by sahith-narahari** [comment]
@aaronc I migrated tests and respective helpers to corresponding modules as suggested. 
I believe it's good to have gaiad commands and keys commands to be in sdk/cli_test for now as they're used in test initialization, but this is definitely something we can modularize in future(any suggestions are welcome)

**Comment by aaronc** [comment]
> @aaronc I migrated tests and respective helpers to corresponding modules as suggested.
> I believe it's good to have gaiad commands and keys commands to be in sdk/cli_test for now as they're used in test initialization, but this is definitely something we can modularize in future(any suggestions are welcome)

Okay, we can start with what's simplest for now.

**Pull request merged**
