### PR TITLE
feat(gov): support v1.Proposal in v1beta1.Proposal.Content

### PR DESCRIPTION
**Pull request by clevinson**
## Description

As discussed in https://github.com/regen-network/governance/pull/16, this PR back ports a fix from @robert-zaremba into Regen's for of the SDK v0.46.7.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by clevinson** [comment]
@robert-zaremba why did you suggest merge instead of cherry pick of `e7dd5e0bdc8aabadb0d4ae13bdb143f92c1cdf4c` ?

This strategy adds in 2 other commits. Are these necessary for the gov PR?
- fix: return anteEvents when postHandler fail (backport #14448) (#14459)
- feat!: remove x/gov/migrations/v046.Migrate_V046_6_To_V046_7 (#14422)

**Review by ryanchristo — APPROVED** [review]
utACK

**Review by robert-zaremba — APPROVED** [review]
utACK

**Comment by robert-zaremba** [comment]
> why did you suggest merge instead of cherry pick of e7dd5e0bdc8aabadb0d4ae13bdb143f92c1cdf4c

You need e6419073fdd4f8341a2ba3a4269cdd4e2d689c3d, which a second commit after 0.46.7
e7dd5e0bdc8aabadb0d4ae13bdb143f92c1cdf4c contains additional ante handler fix.
Once 0.46.8 will be released you can do a again a normal merge - it will look cleaner when you do linear merges.

**Review by ryanchristo — APPROVED** [review]
[tACK](https://hackmd.io/dQLSDStnSMGEnxp-ahXlvg)

**Pull request merged**
