### PR TITLE
chore: merge v0.46.7-regen-2 into release/v0.46.10-regen

### PR DESCRIPTION
**Pull request by ryanchristo**
## Description

This pull request merges the `v0.46.7-regen-2` release into the new `v0.46.10` release branch (created from `v0.46.10`). 

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by clevinson** [comment]
Why is this diff so large? Were there really that many changes that we made to v0.46.7 ? 

I remember stuff w/ Amino, upgrading to require go 1.19, and some other things that we back ported in from v0.47. But surprised that it covers so many files.

**Comment by ryanchristo** [comment]
> Why is this diff so large? Were there really that many changes that we made to v0.46.7 ?

Yup, these are the same changes (and a few less) that we made in https://github.com/regen-network/cosmos-sdk/pull/49

**Comment by ryanchristo** [comment]
The changes made in https://github.com/regen-network/cosmos-sdk/pull/51 were included in the latest on the sdk side.

**Review by clevinson — APPROVED** [review]
Ran through all the commits in this PR and verified that we have everything that was in `release/v0.46.7-regen` branch (additional to the official v0.46.7 release).

**Comment by clevinson** [comment]
Lint PR is failing due to conventional commit check failing on PR title, maybe update that before merging?

**Pull request merged**
